### ISSUE TITLE
Using ZED camera

### ISSUE THREAD

**Issue by salgado** [NVIDIA-ISAAC-ROS/isaac_ros_visual_slam#100]
Hi,

Where can I modify so that can work with a ZED stereo camera ?

**Comment by jaiveersinghNV** [comment]
You can start by running [this launch file](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_visual_slam/blob/main/isaac_ros_visual_slam/launch/isaac_ros_visual_slam.launch.py), which spins up only the VSLAM node. The VSLAM node requires a pair of rectified image topics, which can be produced by the ZED Camera node publishing into a pair of Isaac ROS Image Rectify nodes from [`isaac_ros_image_pipeline`](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_image_pipeline).
