### ISSUE TITLE
Package 'isaac_ros_visual_slam' not found

### ISSUE THREAD

**Issue by sridhargunnam** [NVIDIA-ISAAC-ROS/isaac_ros_visual_slam#103]
Platform: X86_64, ubuntu 22.04 

Error at step 4 in the quick start. 

installation is correctly verified, but upon running "ros2 launch isaac_ros_visual_slam isaac_ros_visual_slam.launch.py", it says packages not found. 

`admin@sgunnam:/workspaces/isaac_ros-dev$ colcon test --executor sequential
Starting >>> isaac_ros_common
Finished <<< isaac_ros_common [0.81s]          
Starting >>> isaac_ros_test
Finished <<< isaac_ros_test [14.9s]            
Starting >>> realsense2_camera_msgs
Finished <<< realsense2_camera_msgs [6.32s]           
Starting >>> isaac_ros_apriltag_interfaces
Finished <<< isaac_ros_apriltag_interfaces [0.75s]           
Starting >>> isaac_ros_bi3d_interfaces
Finished <<< isaac_ros_bi3d_interfaces [0.62s]           
Starting >>> isaac_ros_pointcloud_interfaces
Finished <<< isaac_ros_pointcloud_interfaces [0.47s]           
Starting >>> isaac_ros_tensor_list_interfaces
Finished <<< isaac_ros_tensor_list_interfaces [0.61s]           
Starting >>> realsense2_camera
Finished <<< realsense2_camera [0.04s]           
Starting >>> realsense2_description
Finished <<< realsense2_description [0.04s]

Summary: 9 packages finished [24.8s]
admin@sgunnam:/workspaces/isaac_ros-dev$ ros2 launch isaac_ros_visual_slam isaac_ros_visual_slam.launch.py
Package 'isaac_ros_visual_slam' not found: "package 'isaac_ros_visual_slam' not found, searching: ['/workspaces/isaac_ros-dev/install/realsense2_description', '/workspaces/isaac_ros-dev/install/realsense2_camera', '/workspaces/isaac_ros-dev/install/realsense2_camera_msgs', '/workspaces/isaac_ros-dev/install/isaac_ros_test', '/workspaces/isaac_ros-dev/install/isaac_ros_tensor_list_interfaces', '/workspaces/isaac_ros-dev/install/isaac_ros_pointcloud_interfaces', '/workspaces/isaac_ros-dev/install/isaac_ros_common', '/workspaces/isaac_ros-dev/install/isaac_ros_bi3d_interfaces', '/workspaces/isaac_ros-dev/install/isaac_ros_apriltag_interfaces', '/opt/ros/humble/install']"
admin@sgunnam:/workspaces/isaac_ros-dev$ 
`

**Comment by swapnesh-wani-nvidia** [comment]
Could you try to build it one more time and make sure the built ROS2 workspace is sourced properly?
