### ISSUE TITLE
ROS2 Foxy Distribution

### ISSUE THREAD

**Issue by furkancetiny** [NVIDIA-ISAAC-ROS/isaac_ros_visual_slam#105]
I am using Jetson Nano Orin 8 GB Developer Kit. And it supports the system's ROS2 Foxy distribution. Is there a tutorial to run the system on this distro?

**Comment by swapnesh-wani-nvidia** [comment]
We provide a ready-to-run docker container for Jetson devices that supports ROS2 Humble out of the box. The latest code base is verified on ROS2 Humble. If you want, here is the [link](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_visual_slam/tree/release-ea3-hotfix1) to the older version (EA3 version) which is compatible with ROS2 Foxy. Keep in mind that a few of the latest features might not be there in the older version.
