### ISSUE TITLE
Trouble in saving map when i follow Tutorial for Visual SLAM with Isaac Sim

### ISSUE THREAD

**Issue by Zhaogaog** [NVIDIA-ISAAC-ROS/isaac_ros_visual_slam#106]
I ran the command that 'ros2 action send_goal /visual_slam/save_map isaac_ros_visual_slam_interfaces/action/SaveMap “{map_url: /home/gaozhao/map}” '.In the terminal,it showed’success: true.However,i could not see the expected map in the target directory ‘home/gaozhao’ or in ‘home/gaozhao/map’.Except for this,anything else seems to go well!
HELP!!!What is the problem?
![fcc4fd5d95d89740fa57f4edce1c8831ba020b49_2_1380x774](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_visual_slam/assets/103256521/bbd5b910-c1ca-45cb-91b9-d8f646cc9eb7)
![b033cb0f75fc6b1697dfc051925662eec82e2d07_2_1380x774](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_visual_slam/assets/103256521/b2373457-5c3e-405d-b963-81f5a8231e87)
![4a4c42a67a3e72fefe3d18bc53e743428640fcbf_2_1380x774](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_visual_slam/assets/103256521/ff4368f7-fcea-4537-967d-7710a6611d88)

**Comment by swapnesh-wani-nvidia** [comment]
Looks like you are trying to find the saved map on your host machine instead you should search for the saved map inside the docker container.
