### ISSUE TITLE
ERROR [5/8] RUN chmod +x /opt/realsense/build-librealsense.sh && /opt/realsense/build-librealsense.sh

### ISSUE THREAD

**Issue by Wilson-shuo** [NVIDIA-ISAAC-ROS/isaac_ros_visual_slam#109]
I was following the instruction on this page [(https://github.com/NVIDIA-ISAAC-ROS/.github/blob/main/profile/realsense-setup.md)]
At Step 5 ,I was trying to launch the docker.
But it keeps going wrong and i can not build base image.
Also,I see that script is trying to install realsense SDK 2.54, but realsense-ros 4.51 only support realsense SDK 2.51.
How to fix that? 
![Screenshot from 2023-08-11 23-18-20](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_visual_slam/assets/24606639/c5cc1a74-5f36-4441-858e-5e6593e57426)

**Comment by swapnesh-wani-nvidia** [comment]
This looks like a transient failure (unable to pull the appropriate build script) could you try running it again?
