### ISSUE TITLE
Elbrus Slam Whitepaper

### ISSUE THREAD

**Issue by ikhann** [NVIDIA-ISAAC-ROS/isaac_ros_visual_slam#112]
Hi,
I would like to better understand the algorithm. 
Can you please provide me with the Elbrus Slam Whitepaper?

**Comment by jaiveersinghNV** [comment]
We have not currently published any whitepaper for cuVSLAM. If you are interested in understanding how cuVSLAM could support your business use case, please [contact NVIDIA](https://developer.nvidia.com/isaac-platform-contact-us-form).
