### ISSUE TITLE
VSLAM with Nanoowl

### ISSUE THREAD

**Issue by IamShubhamGupto** [NVIDIA-ISAAC-ROS/isaac_ros_visual_slam#121]
Hey

SLAM can be implemented on the orin nano using just nav2 library but this repo seems to be optimized for the orin nano. Apart from localization, I want the orin to be also be able to run an object detection node using https://github.com/NVIDIA-AI-IOT/nanoowl.

It is physically capable of running both these projects simultaneously? 

Thank you,

**Comment by hemalshahNV** [comment]
Yes, you likely would have enough compute on an Orin Nano 8GB to run Nav2 (lidar localization) and the NanoOWL library, sure, but that's just an estimate. You'd have to try it to confirm that you have overhead for your application.
