### ISSUE TITLE
Unable to recover after "Visual tracking is lost"

### ISSUE THREAD

**Issue by sandeepdutta** [NVIDIA-ISAAC-ROS/isaac_ros_visual_slam#136]
Hello,
I am trying to use this package with ZED mini camera on Orin AGX. The system works fine 
till we hit a situation when "**Visual tracking is lost**"  this can happen due to many reasons,
(robot wondering to close to a featureless wall, enters low lighting area), Once this happens though
the visual slam is unable to recover. I am using IMU fusion from the ZED camera. I have tracked the IMU Odometry
it seems to be generating the correct data. Any work arounds or suggestions.

Sandeep

**Comment by swapnesh-wani-nvidia** [comment]
Here is my interpretation based on what is described. Once the tracker is lost. It will be in a mode where the odometry estimates won't match the ground truth. At that point, you can call the reset odometry service to reinitialize the tracker and vslam odometry session.
