### ISSUE TITLE
ros1 support

### ISSUE THREAD

**Issue by omerwaxman** [NVIDIA-ISAAC-ROS/isaac_ros_visual_slam#14]
does this package has a ros1 version?

**Comment by hemalshahNV** [comment]
We only support ROS2 but you should be able to port to ROS1 if needed.
________________________________
From: omerwaxman ***@***.***>
Sent: Sunday, March 13, 2022 8:29:21 AM
To: NVIDIA-ISAAC-ROS/isaac_ros_visual_odometry ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [NVIDIA-ISAAC-ROS/isaac_ros_visual_odometry] ros1 support (Issue #14)


does this package has a ros1 version?

—
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNVIDIA-ISAAC-ROS%2Fisaac_ros_visual_odometry%2Fissues%2F14&data=04%7C01%7Chemals%40nvidia.com%7C607c80a628014222114b08da05064001%7C43083d15727340c1b7db39efd9ccc17a%7C0%7C0%7C637827821647868571%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=NVqeWPtcMiZAI14oe2XxfOYcepQ1mgDM699JBpeabhw%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASS44RVLKXFRLNCQYDB3P3DU7YCVDANCNFSM5QTPM2HQ&data=04%7C01%7Chemals%40nvidia.com%7C607c80a628014222114b08da05064001%7C43083d15727340c1b7db39efd9ccc17a%7C0%7C0%7C637827821647868571%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ySgyCbKqUHuEPvaGiujv%2FtrnPL8DuaT7beQ80BPlM%2BM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Chemals%40nvidia.com%7C607c80a628014222114b08da05064001%7C43083d15727340c1b7db39efd9ccc17a%7C0%7C0%7C637827821647868571%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=tAboQ3tegG7TmnoOPpQhp%2BrNhDl%2FVYdZbEq4ht%2B6DS4%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Chemals%40nvidia.com%7C607c80a628014222114b08da05064001%7C43083d15727340c1b7db39efd9ccc17a%7C0%7C0%7C637827821647868571%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2nh%2FToQ3MAMdcdUSmod%2BhvXSkK%2F5OgieJkLE2vtREEY%3D&reserved=0>.

**Comment by canberkgurel** [comment]
@hemalshahNV how should the porting be done?

**Comment by hemalshahNV** [comment]
The core Elbrus library is not ROS-specific. Using the source from our ROS2 nodes, you should be able to write a ROS1 node that wraps the core libraries in the same manner as we did.
