### ISSUE TITLE
Problem with the quickstart

### ISSUE THREAD

**Issue by raffy952** [NVIDIA-ISAAC-ROS/isaac_ros_visual_slam#153]
I'm trying to launch the command `ros2 launch isaac_ros_visual_slam isaac_ros_visual_slam.launch.py` in the  `isaac_ros_visual_slam` quickstart but when i run the command `ros2 bag play src/isaac_ros_visual_slam/isaac_ros_visual_slam/test/test_cases/rosbags/small_pol_test/` , in the terminal of the first command i got this error:
`[ERROR] [component_container-1]: process has died [pid 990, exit code -6, cmd '/opt/ros/humble/lib/rclcpp_components/component_container --ros-args -r __node:=visual_slam_launch_container -r __ns:=/'].`

In the terminal of ros2 bag i got this:
 `[INFO] [1709245750.793296040] [rosbag2_storage]: Opened database 'src/isaac_ros_visual_slam/isaac_ros_visual_slam/test/test_cases/rosbags/small_pol_test/small_pol_test_0.db3' for READ_ONLY.
[INFO] [1709245750.793350749] [rosbag2_player]: Set rate to 1
[INFO] [1709245750.797600662] [rosbag2_player]: Adding keyboard callbacks.
[INFO] [1709245750.797623855] [rosbag2_player]: Press SPACE for Pause/Resume
[INFO] [1709245750.797635200] [rosbag2_player]: Press CURSOR_RIGHT for Play Next Message
[INFO] [1709245750.797644764] [rosbag2_player]: Press CURSOR_UP for Increase Rate 10%
[INFO] [1709245750.797653562] [rosbag2_player]: Press CURSOR_DOWN for Decrease Rate 10%
[INFO] [1709245750.798002561] [rosbag2_storage]: Opened database 'src/isaac_ros_visual_slam/isaac_ros_visual_slam/test/test_cases/rosbags/small_pol_test/small_pol_test_0.db3' for READ_ONLY.`

Ubuntu 22.04
NVIDIA-SMI 535.161.07             Driver Version: 535.161.07   CUDA Version: 12.2 
NVIDIA GeForce MX130

**Comment by jaiveersinghNV** [comment]
Hi @raffy952 ,

Unfortunately, it looks like you are running on an MX130 Maxwell generation GPU. As specified [here](https://nvidia-isaac-ros.github.io/getting_started/hardware_setup/compute/index.html#x86-platforms), we require Volta or higher for running Isaac ROS.

Can you try running this on a more modern GPU?
