### ISSUE TITLE
Few errors when using realsense camera

### ISSUE THREAD

**Issue by beomsu7** [NVIDIA-ISAAC-ROS/isaac_ros_visual_slam#19]
I'm using docker and realsense d435i.
After setting up everyting, launched isaac_ros_visual_slam_realsense.launch.py and there were few erros.
* * *
* * * 
   
**error 1**. parameter type error

[realsense2_camera_node-2]   what():  parameter 'stereo_module.emitter_enabled' has invalid type: expected [integer] got [bool]
![image](https://user-images.githubusercontent.com/72853382/160958360-5ca45b1b-df1b-46e1-8904-627ca1c990a7.png)

* * * 
**edit for error1**. type change

I changed 'stereo_module.emitter_enabled' from 'False' to '0',  after changing it's fine
![image](https://user-images.githubusercontent.com/72853382/160958782-8fd12de6-e3a2-4b44-abfd-62e2ec0416e3.png)

* * * 
* * * 
**error 2**. In the launch file, there is no declaration about namesapce, so when launching the file, the tf tree looks like this
![image](https://user-images.githubusercontent.com/72853382/160960058-df7461ae-8087-4b55-8e01-2145227f8533.png)
* * * 
**edit1 for error 2**. added namesapce declaration(failed)
![image](https://user-images.githubusercontent.com/72853382/160960893-c4cc9b7c-7ec9-42ce-9221-202d82a76743.png)
![image](https://user-images.githubusercontent.com/72853382/160960768-868468f2-d5b4-4ccb-8021-e8af97606f96.png)
* * * 
**edit2 for error 2**. edited the name of frame, it worked for me
![image](https://user-images.githubusercontent.com/72853382/160961106-118c6907-19bb-4265-83ba-76de7e77ee26.png)
![image](https://user-images.githubusercontent.com/72853382/160961292-b10045ec-6a93-4be0-98ac-d9a6ce987279.png)   
* * * 

As a result, I think in this case(error 2) adding namespace is the right way, but it didn't work well
So Is there anything what I need to check or miss?

**Comment by hemalshahNV** [comment]
The Intel Realsense package had some breaking changes for parameter names. These should be fixed in the latest version of Isaac ROS Visual SLAM if you're able to try it out.
