### ISSUE TITLE
Could not find the resource 'realsense2_camera

### ISSUE THREAD

**Issue by patrickpoirier51** [NVIDIA-ISAAC-ROS/isaac_ros_visual_slam#2]
Hello,

Trying to run the example with D435 but it is not found

Resloved:  We have to run **git lfs pull**  in each Isaac ROS repository
Just spent 6 hours finding out... :-(

**PLEASE ADD TO THE INSTALLATION**

**Comment by hemalshahNV** [comment]
Thanks for posting the resolution and apologies for the frustration. Did you happen to install git lfs before you cloned the repositories? Could you post the error you ran into? Git LFS brings in binary assets hosted in the repository but the realsense2_camera package itself is not hosted by Git LFS however.

**Comment by patrickpoirier51** [comment]
Thanks for fast reply
Actually I could not get the camera being recognized with rs-enumerates at first try and it was working at second reload with git lfs pull

But still I could not get the realsense lauch started and I had to intall the intel ros2 stuff to get it started

Now I am fighting to get the rviz installed as it is not on the omage ?!? And it fails while building as it is trying to find build parameters

**Comment by hemalshahNV** [comment]
You'll want to run rviz2 on an x86 machine connected to your Jetson. rviz2 is not available for JP4.6 (Ubuntu 18.04) and not in the aarch64 container for Jetson. As for the Realsense camera issues, there have been recent updates to their public release, but we have not run into any issues. Which Realsense are you using?

**Comment by patrickpoirier51** [comment]
Hello,
Yes, that is what I am trying to do at the moment but I am facing issues with running RVIZ2 on WSL2... so I will probably load it on a clean UBUNTU partition. 

 I am using  a D435i and it seems to be working pretty good.

**Comment by patrickpoirier51** [comment]
Well...  finally ;-P 
I built ROS2 on a fresh UBUNTU  on my Desktop and  added **_export ROS_DOMAIN_ID=5_** to both system
Launched rviz2 and connected to **odom**


![image](https://user-images.githubusercontent.com/12484190/140077255-66645f83-053c-4218-a9f7-1c57c11647e8.png)

**Comment by AndreV84** [comment]
it misses the ros package
https://github.com/IntelRealSense/realsense-ros/archive/refs/tags/v4.0.0-beta.tar.gz
then trying to build it manually it won't find the diagnostics updater package
[on Jetson]
```
sudo apt install ros-foxy-diagnostic-updater ros-foxy-diagnostic-msgs ros-foxy-rclcpp ros-foxy-rclpy ros-foxy-std-msgs
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ros-foxy-diagnostic-msgs : Depends: libpython3.8 (>= 3.8.2) but it is not going to be installed
                            Depends: ros-foxy-builtin-interfaces but it is not going to be installed
                            Depends: ros-foxy-geometry-msgs but it is not going to be installed
                            Depends: ros-foxy-rosidl-default-runtime but it is not going to be installed
 ros-foxy-rclcpp : Depends: ros-foxy-builtin-interfaces but it is not going to be installed
                   Depends: ros-foxy-libstatistics-collector but it is not going to be installed
                   Depends: ros-foxy-rcl but it is not going to be installed
                   Depends: ros-foxy-rcl-interfaces but it is not going to be installed
                   Depends: ros-foxy-rosgraph-msgs but it is not going to be installed
                   Depends: ros-foxy-statistics-msgs but it is not going to be installed
 ros-foxy-rclpy : Depends: libpython3.8 (>= 3.8.2) but it is not going to be installed
                  Depends: ros-foxy-builtin-interfaces but it is not going to be installed
                  Depends: ros-foxy-rcl but it is not going to be installed
                  Depends: ros-foxy-rcl-action but it is not going to be installed
                  Depends: ros-foxy-rcl-interfaces but it is not going to be installed
                  Depends: ros-foxy-rmw-implementation but it is not going to be installed
                  Depends: ros-foxy-rosgraph-msgs but it is not going to be installed
                  Depends: ros-foxy-unique-identifier-msgs but it is not going to be installed
 ros-foxy-std-msgs : Depends: libpython3.8 (>= 3.8.2) but it is not going to be installed
                     Depends: ros-foxy-builtin-interfaces but it is not going to be installed
                     Depends: ros-foxy-rosidl-default-runtime but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by AndreV84** [comment]
@hemalshahNV 
as per my experience it doesn't get installed to isaac_ros-dev Docker containe /workspaces/isaac_ros-dev

**Comment by AndreV84** [comment]
@hemalshahNV Thank you for letting me know!

**Comment by GuillaumeLaine** [comment]
Hi @hemalshahNV ,
I'm also having a similar issue using the Docker container, Realsense D455 and Jetson AGX. I get:
```
ament_index_python.packages.PackageNotFoundError: "package 'realsense2_camera' not found, 
searching: ['/workspaces/isaac_ros-dev/install/isaac_ros_visual_slam', '/workspaces/isaac_ros-dev/install/isaac_ros_visual_slam_interfaces', '/workspaces/isaac_ros-dev/install/isaac_ros_test', '/workspaces/isaac_ros-dev/install/isaac_ros_image_pipeline', '/workspaces/isaac_ros-dev/install/isaac_ros_stereo_image_proc', '/workspaces/isaac_ros-dev/install/isaac_ros_nvengine', '/workspaces/isaac_ros-dev/install/isaac_ros_nvengine_interfaces', '/workspaces/isaac_ros-dev/install/isaac_ros_image_proc', '/workspaces/isaac_ros-dev/install/isaac_ros_common', '/opt/ros/foxy/install']"
```
when trying to launch:
`ros2 launch isaac_ros_visual_slam isaac_ros_visual_slam_realsense.launch.py` 
within the Docker container.

You suggested that `realsense2_camera` and other `realsense-ros2` packages should be installed in the Docker container, but that does not seem to be the case for me neither? I've tried exiting the container, re-plugging the Realsense D455 to the Jetson AGX (working in realsense-viewer), re-entering the container, re-running steps 4. rosdep install & 5. colcon build, sourcing the workspace but I still get that the package is missing? What have I overlooked?

In the meantime I will try to build `realsense2_camera` manually as done by others.

**Comment by AndreV84** [comment]
@GuillaumeLaine 
u mau also try  apt-get install ros-$ROS_DISTRO-realsense2-camera
if it is present in apt repositories it will work too. However to build from source is more useable typically.

**Comment by GuillaumeLaine** [comment]
Thanks for the quick reply @AndreV84 
Unfortunately the repo seem to be unavailable for foxy (and galactic) at the moment. I get:
`apt-get install -y ros-$ROS_DISTRO-realsense2-camera`
This seems to be known issue: https://github.com/IntelRealSense/realsense-ros/issues/1814

**Comment by AndreV84** [comment]
right
However you should be able first to install realsense sdk [ either from apt or from sources]
then bukld workspace woth ros realsense node

**Comment by GuillaumeLaine** [comment]
@AndreV84 Thanks a lot! That worked for me.
However building the realsense ros package did not work immediately. For future readers, the realsense ros package readme suggests running:
`rosdep install -i --from-path src --rosdistro $_ros_dist --skip-keys=librealsense2 -y`
That did not work, but running:
`rosdep install -i --from-path src --rosdistro $ROS_DISTRO --skip-keys "librealsense2 xacro" -y`
worked instead.

**Comment by jn128c** [comment]
I`m stuck here...
Started all over with fresh image of container, edit config file for build with realsense. It tried to build realsense but failed with errors. Manual install with vcpkg failed at point of kernel patch because of not supported kernel.
apt-get doesnt find the repositories. 
build the source of realsense_SDK faild because of Cmake Ninja which I cant get installed. 
Could someone explain a method for installing the realsense sdk inside of the container?
I´m on Orin DevKit Jetpack 5.0.2
Camera is working outside of container...
