### ISSUE TITLE
The passed action type is invalid

### ISSUE THREAD

**Issue by hpf9017** [NVIDIA-ISAAC-ROS/isaac_ros_visual_slam#32]
when call the save map action, it occurs an error.

![Screenshot from 2022-06-23 18-05-58](https://user-images.githubusercontent.com/17041625/175274761-8a255c84-b8fb-4b21-8626-32d48ab564b4.png)
![Screenshot from 2022-06-23 18-06-20](https://user-images.githubusercontent.com/17041625/175274787-ba512c15-d6b9-41ea-977d-13cf3510244a.png)

**Comment by hemalshahNV** [comment]
Please make sure you've sourced the workspace with the interface definitions before using the ros2 CLI. The string format of your message is missing a key from what you posted: 
```
ros2 action send_goal /visual_slam/save_map isaac_ros_visual_slam_interfaces/action/SaveMap "{map_url: /tmp/isaac-vslam-map}"
```

**Comment by ztbupt** [comment]
I meet the same issue. The HW is Orin NX 8G with realsense camera. The Rviz shows good. But savemap action reports "The passed action type is invalid". I used the below cmd
ros2 action send_goal /visual_slam/save_map isaac_ros_visual_slam_interfaces/action/SaveMap "{map_url: /tmp/map}"

how to solve it?

**Comment by ztbupt** [comment]
> I meet the same issue. The HW is Orin NX 8G with realsense camera. The Rviz shows good. But savemap action reports "The passed action type is invalid". I used the below cmd ros2 action send_goal /visual_slam/save_map isaac_ros_visual_slam_interfaces/action/SaveMap "{map_url: /tmp/map}"
> 
> how to solve it?

And the action is below:

admin@em3-desktop:/tmp/map$ ros2 action list
/visual_slam/load_map_and_localize
/visual_slam/save_map
admin@em3-desktop:/tmp/map$ ros2 action info save_map
Action: save_map
Action clients: 0
Action servers: 0
admin@em3-desktop:/tmp/map$ ros2 action info load_map_and_localize
Action: load_map_and_localize
Action clients: 0
Action servers: 0
