### ISSUE TITLE
Maximum distance to distinguishable features

### ISSUE THREAD

**Issue by jvasi** [NVIDIA-ISAAC-ROS/isaac_ros_visual_slam#33]
Hi,

We're evaluating Visual SLAM for large warehouse areas where the distance to the nearest visible objects can be up to 100 meters.

What is the limitation for the distance of the features detected on camera? In other words, how far can a distinguishable feature be in order for the Visual SLAM to work?

Unfortunately, this information doesn't seem to be available anywhere.

**Comment by gordongrigor** [comment]
This is a function of your stereo camera selection, not Visual SLAM.  Look at the specification for your stereo camera, and what the maximum depth detected is.  It's very likely less than 100m.

From a civil engineering perspective most buildings have a requirement which would put a structural pillar at <30m.  Unless your sensors have a narrow field of view, it should be less than 100m indoors.  It's possible to have >=100m outdoors, but then GPS becomes a localization option. 

You could derive your perception requirements from the domain of operation, and then use those requirements to inform the selection of sensors for perception.
