### ISSUE TITLE
Goal was rejected when saving map

### ISSUE THREAD

**Issue by hpf9017** [NVIDIA-ISAAC-ROS/isaac_ros_visual_slam#39]
ros2 action send_goal /visual_slam/save_map isaac_ros_visual_slam_interfaces/action/SaveMap "{map_url: /workspaces/isaac_ros-dev/map}"
Waiting for an action server to become available...
Sending goal:
     map_url: /workspaces/isaac_ros-dev/map

Goal was rejected.

**Comment by hemalshahNV** [comment]
Does the map_url directory exist and writeable? It would be easier to just use `/tmp` instead if that works.
