### ISSUE TITLE
does the last release (DP) of isaac_ros_visual_slam still support galactic or just Humble?

### ISSUE THREAD

**Issue by geoporus-karelics** [NVIDIA-ISAAC-ROS/isaac_ros_visual_slam#45]
Hello!

I started using the isaac_ros_visual_slam package around 2 months ago, before the latest release that supports Humble. My application still uses ROS2 Galactic at its core and so, the release I used at the time (v0.9.3-ea3) has been working well for me. Since then I didn't have time to check whether the latest stable release also supports Galactic, and in the documentation, there is no mention of this. So, does it support it or not?

Thank you!

**Comment by hemalshahNV** [comment]
Isaac ROS EA3 supported only ROS2 Foxy but could in theory have worked fine on Galactic with minor modifications. Isaac ROS DP packages, however, takes advantage of new features in ROS2 Humble and wouldn't be able to run on an earlier release.
