### ISSUE TITLE
 isaac_ros_visual_slam as simulation return [CUDA] failure

### ISSUE THREAD

**Issue by muratkoc503** [NVIDIA-ISAAC-ROS/isaac_ros_visual_slam#47]
Hi,
I am working with isaac_ros_visual_slam package and Gazebo. 
![Screenshot from 2022-09-05 15-08-04](https://user-images.githubusercontent.com/75611653/188445929-63e497e8-9c54-4ffc-925b-a5eebe9848a4.png)

My error:
[component_container-1] [INFO] [1662379434.366503061] [visual_slam_node]: Use use_gpu: true
[component_container-1] [ERROR] 140409917632320 [CUDA] failure: 13, file: /home/akorovko/Code/elbrus/src/modules/cuda_modules/src/lk_tracker.cpp, line: 9

Also, i use pytorch environment with cuda.

Thanks for reply.

**Comment by muratkoc503** [comment]
I work on Ros Galactic. Maybe this is reason of my error. i dont know.

**Comment by hemalshahNV** [comment]
Could you describe the platform you're running on? Are you running within the Isaac ROS Dev base Docker container or natively on host? It looks like an x86 machine running ROS2 Humble (not Galactic which is incompatible) but with which NVIDIA GPU available for CUDA?

**Comment by muratkoc503** [comment]
My knowledge is not good at docker. So, sorry. I work on 64 bit on computer.(laptop). CUDA Version: 11.7. I will look tomorrow. Thanks for Humble case.
**nvidia-smi:**
![Screenshot from 2022-09-06 22-46-05](https://user-images.githubusercontent.com/75611653/188725119-f3b6e260-7119-4b21-8b82-97f8c42836ce.png)

**Comment by muratkoc503** [comment]
I try to run rosbag example which is "small_pool_test". But, it give same error. My GPU is NVIDIA GeForce MX110. Is it enough for isaac_ros_visual_slam package? Also, i try path as "nvidia-container-runtime" and "/usr/build/nvidia-container-runtime", but this is not work. I install nvidia-container-runtime package is seen belove: I use Ubuntu focal(20.04) and jammy(22.04). But bionic version is installed. I dont know, what is the reason of my error. I doubt from my nvidia-container-runtime. Also i try Ros2 Galactic and Humble.

![Screenshot from 2022-09-08 18-53-34](https://user-images.githubusercontent.com/75611653/189168688-86999041-28f6-4943-be37-99146209ce26.png)

![Screenshot from 2022-09-08 18-58-17](https://user-images.githubusercontent.com/75611653/189169517-c7c09a7b-cd87-4fda-ada3-2ca406a973f4.png)

![Screenshot from 2022-09-08 18-59-21](https://user-images.githubusercontent.com/75611653/189169759-5c0c06e0-b835-456e-81c5-6e6173772f59.png)

**Comment by muratkoc503** [comment]
Also, i install nvidia-container-runtime to native computer. I dont install nvidia-container-runtime to this(isaac_ros_visual_slam) Docker container. Does the nvidia-container-runtime installing in the Docker container is necessary?

**Comment by hemalshahNV** [comment]
It appears you're running this on a Maxwell architecture GPU. We think this may not be recent enough for Isaac ROS Visual SLAM to work with. Can you try running on a Volta or newer GPU? We'll work on a more graceful failure message if this is indeed the problem you're running into.

**Comment by muratkoc503** [comment]
I am not working with Gazebo, i am running bag file now:

`source /workspaces/isaac_ros-dev/install/setup.bash && \
   ros2 bag play src/isaac_ros_visual_slam/isaac_ros_visual_slam/test/test_cases/rosbags/small_pol_test/`

Also, My Gazebo doesn't use GPU. Probably i dont use GPU correctly.

**watch nvidia-smi:** (on natural computer)
![Screenshot from 2022-09-13 08-15-04](https://user-images.githubusercontent.com/75611653/189831155-f3f10f1f-72e4-4110-86a2-2b67ce22667d.png)

**watch nvidia-smi:** (in docker container)
![Screenshot from 2022-09-13 09-48-17](https://user-images.githubusercontent.com/75611653/189831454-c0bfa3cf-b75d-4432-ac38-2e9d3f18695b.png)

**top:** (in docker container)
![Screenshot from 2022-09-13 09-49-49](https://user-images.githubusercontent.com/75611653/189831656-43d332d8-46ba-4b72-8dc6-57896c5d4f9a.png)

component container, rviz2 and all other program doesn use GPU. Only X-server and office program use GPU.

![Screenshot from 2022-09-13 08-11-32](https://user-images.githubusercontent.com/75611653/189832046-2a8babde-b8e0-4396-9fe2-592b2c1028a5.png)

Also, i have 2GB memory. But only 3MB is used. Gazebo doesn't use GPU. Accually, i have a nvidia-driver
I try to solve GPU using with program (ex: Gazeob).

**Comment by muratkoc503** [comment]
I think, my installation is correct. Because i test my GPU(Nvidia Container) at my native computer and any docker container.

**Run GPU in native computer:** (BlackScholes sample)
![Screenshot from 2022-09-13 23-13-09](https://user-images.githubusercontent.com/75611653/190131183-28a57559-b3c6-486f-b0ab-cf66eba7894e.png)

**Run GPU in docker container:** (ros_caffe sample)
![Screenshot from 2022-09-14 11-17-19](https://user-images.githubusercontent.com/75611653/190131529-9bdbc9ae-f899-44e2-91f5-70ff2badd3c7.png)

Also, i run optional command after installing isaac_ros_visual_slam package:
`colcon test --executor sequential
`

This command get below error:
```
Starting >>> isaac_ros_visual_slam
--- stderr: isaac_ros_visual_slam                         
Errors while running CTest
Output from these tests are in: /workspaces/isaac_ros-dev/build/isaac_ros_visual_slam/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
Finished <<< isaac_ros_visual_slam [18.2s]	[ with test failures ]
```

So, i read log file. i see 3 errror message in : colcon test --executor sequential command

```
[component_container-1] [ERROR] 140288154709824 [CUDA] failure: 13, file: /home/akorovko/Code/elbrus/src/modules/cuda_modules/src/lk_tracker.cpp, line: 9
[ERROR] [component_container-1]: process has died [pid 44573, exit code -6, cmd '/opt/ros/humble/install/lib/rclcpp_components/component_container --ros-args -r __node:=visual_slam_container -r __ns:=/'].
[ERROR] 140288154709824 [CUDA] failure: 13, file: /home/akorovko/Code/elbrus/src/modules/cuda_modules/src/lk_tracker.cpp, line: 9
```
Also, i didn't can't try with Volta or new GPU. I have only this computer. Probably, my computer doesn't support this. I don't know. I have 2GB GPU memory.

**Comment by muratkoc503** [comment]
I try to Ros BAG sample in **isaac_ros_nvblox** package (nvblox_pol sample).
It work correct for me.

**Result:**
**Run GPU isaac_ros_nvblox:**
![Screenshot from 2022-09-14 14-41-54](https://user-images.githubusercontent.com/75611653/190146604-5e2e1d09-aff3-4777-86cc-743221460931.png)

**Rviz Result:**
![Screenshot from 2022-09-14 14-40-13](https://user-images.githubusercontent.com/75611653/190146773-137a1961-c518-4cc3-9ab8-d52da180721a.png)

Probably, [CUDA] failure: 13, file: /home/akorovko/Code/elbrus/src/modules/cuda_modules/src/lk_tracker.cpp, line: 9 error interested in isaac_ros_visual_slam package. isaac_ros_nvblox work my computer with GPU.

**Comment by jaiveersinghNV** [comment]
Isaac ROS Visual SLAM is only compatible with Volta and newer GPU architectures.

**Comment by madgrizzle** [comment]
Can someone explain why a Volta (or newer) GPU is required?  I've installed and have successfully run this on a Tesla P4 that is based on Pascal.  I've yet to incorporate it into my robot, but what specifically does the Volta architecture provide that's missing on the Pascal that's in use by visual slam?
