### ISSUE TITLE
Robot Self-shadowing

### ISSUE THREAD

**Issue by Srijal97** [NVIDIA-ISAAC-ROS/isaac_ros_visual_slam#49]
Hey!

This is more of a question rather than an issue, but I couldn't seem to find a forum for this.

I have not used this package yet, but with ORB_SLAM2, I have this issue where if the shadow of my robot falls within the image FOV, features from the shadow cause ORB_SLAM2 to think that the robot isn't moving as much as it actually does. This has been a deal breaker and I am curious to know if this package will perform better in such situations. One key difference is that ORB_SLAM2 does not use IMU inertial inputs so maybe that is better handled here. Has this situation been encountered in any of your tests?

**Comment by jaiveersinghNV** [comment]
We have not encountered this issue in any of our tests, but please do keep us informed on how your comparison is going.
