### ISSUE TITLE
Evaluation the result  & GT pose 

### ISSUE THREAD

**Issue by Harin99** [NVIDIA-ISAAC-ROS/isaac_ros_visual_slam#50]
Thank you for your great work! 

And then how did you evaluate your result? 
**Did you get the gt pose in the isaac sim?**

I want to use yours using our own dataset generated in isaac sim, we couldn't get the gt pose in isaac sim now.
because /tf & /odom is not gt (based on AMCL) and we couldn't find any alternatives. 

If you did the evaluation your algorithm, how did you get the GT pose in isaac sim? 

Thank you!

**Comment by swapnesh-wani-nvidia** [comment]
You can just record Isaac Sim data without running VSLAM and collect the ground truth (/tf and /odom) in a ROS bag and use the same bag to evaluate VSLAM. Of course, you have to rename the frame_names either in Isaac Sim or VLSLAM for comparison.
