### ISSUE TITLE
Repository not working

### ISSUE THREAD

**Issue by andresancal** [NVIDIA-ISAAC-ROS/isaac_ros_visual_slam#51]
The ament_cmake can not be found.
I have already tried to source the opt/ros/humble/setup.bash 

![Screenshot from 2022-10-17 20-51-51](https://user-images.githubusercontent.com/56458587/196316862-6a96c01a-db81-44cc-8880-6aa14b122ea5.png)

**Comment by hemalshahNV** [comment]
Are you using the Isaac ROS Dev base images or a custom install of ROS2 Humble? Can you build any package if colcon can't find ament_cmake?

**Comment by jaiveersinghNV** [comment]
Could you please run: `ros2 pkg prefix ament_cmake_auto`, and see if ROS2 is able to find this path installed? When I run this inside the Docker container on my machine, I get the expected installation path of `/opt/ros/humble/install`.

**Comment by jn128c** [comment]
Had the same issue, fix your folder/file permissions. Or try sudo.
