### ISSUE TITLE
How can I evaluate with the KITTI dataset?

### ISSUE THREAD

**Issue by Corufa** [NVIDIA-ISAAC-ROS/isaac_ros_visual_slam#60]
Currently I was able to try the ros bag file provided with Quickstart.
I want to evaluate with KITTI, but I don't how to handle it.
How can I do a isaac_ros_visual_slam with KITTI?

Thank you!

**Comment by swapnesh-wani-nvidia** [comment]
You can do so by creating a ros bag from KITTI images to feed to isaac_ros_visual_slam. Make sure the timestamps are in correct order and are synchronized for left and right images. Also, we have published our results for KITTI benchmark which you can see [here](https://www.cvlibs.net/datasets/kitti/eval_odometry.php?highlight=Elbrus#:~:text=54-,IsaacElbrusGPUSLAM,-0.94%20%25).

**Comment by Corufa** [comment]
How didi you create the KITTI ros bag?

**Comment by Corufa** [comment]
I could try it with KITTI.

**Comment by rocker12121** [comment]
Hello. Can you please provide more detail on how to run with kitti? or the bag files if possible?

**Comment by Corufa** [comment]
Hello. I don't have a ROSbag file because I've already finished the project.
