### ISSUE TITLE
How can I run isaac_ros_visual_slam docker image with ROS Noetic host machine?

### ISSUE THREAD

**Issue by Mikor-mkr** [NVIDIA-ISAAC-ROS/isaac_ros_visual_slam#73]
Hello everyone, 

as the title says, can someone provide some info of the necessary actions I need to make in order to provide ros topics comming from my host machine which is using ROS Noetic to the docker image with the isaac_ros_visual_slam?

Thanks in advance.

**Comment by hemalshahNV** [comment]
From within the Isaac ROS Dev base container, you could run Isaac ROS Visual SLAM and the ROS2<->ROS1 bridge ([here](https://github.com/ros2/ros1_bridge)). `run_dev.sh` will launch the container with host network so you should then be able to see all of the topics from your Noetic application running elsewhere (on the host machine or in a different container with host network). 

Any reason to not just move to ROS 2 Humble for your whole application though?
