### ISSUE TITLE
Error while building isaac ros visual slam

### ISSUE THREAD

**Issue by itsghaniz** [NVIDIA-ISAAC-ROS/isaac_ros_visual_slam#86]
I am trying to use isaac ros visual slam on jetson nano.  I am using the method mentioned on the github page https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_visual_slam. I am using the docker as mentioned in the official tutorial. I was able to build the isaac_ros_common package and the isaac_ros_nitro package, but the isaac_ros_visual_slam doesnt get built and gives the error as

collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/isaac_ros_visual_slam.dir/build.make:388: isaac_ros_visual_slam] Error 1
make[1]: *** [CMakeFiles/Makefile2:165: CMakeFiles/isaac_ros_visual_slam.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
---
Failed   <<< isaac_ros_visual_slam [3.24s, exited with code 2]

can anyone please suggest what I might be doing wrong?
thanks in advance.

**Comment by jaiveersinghNV** [comment]
Could you please provide the full build logs here? With just this snippet, it's difficult to tell what the exact error is.
