### ISSUE TITLE
What happens after "Tracker is lost" warning?

### ISSUE THREAD

**Issue by eMrazSVK** [NVIDIA-ISAAC-ROS/isaac_ros_visual_slam#9]
Hello,

I guess the title is self-explaining. Just to add to my question - is it possible to re-gain tracking pose somehow after this warning is sent? Because I get enormously big numbers after tracker is lost in `rectified_pose`. Let's say `4x10^27` in translation axes.

**Comment by eMrazSVK** [comment]
One more addition - smooth_pose continues to work correctly (with accumulated drift ofc).

**Comment by swapnesh-wani-nvidia** [comment]
Hi @eMrazSVK, 

It is possible that tracking can resume, however, be aware that during the period where tracking is lost VO can drift. If it drifts too much, it is advisable to restart the VO. For the smooth pose, as you mentioned in the question, it will continue to give out the pose with accumulated drift.
