### ISSUE TITLE
No progress on action: save_map

### ISSUE THREAD

**Issue by tom-deBach** [NVIDIA-ISAAC-ROS/isaac_ros_visual_slam#93]
Hello, 
I am running the isaac VSLAM together with nvblox.
When I try to save the map it starts the action, but it seems that it does not work properly.
It accepts the goal, but nothing happens then:

This is the message I receive when calling the action:

admin@tegra-ubuntu:/workspaces/isaac_ros-dev$ ros2 action send_goal /visual_slam/save_map isaac_ros_visual_slam_interfaces/action/SaveMap "{map_url: /home/nvidia/workspaces/isaac_ros-dev/maps}" --feedback
Waiting for an action server to become available...
Sending goal:
     map_url: /home/nvidia/workspaces/isaac_ros-dev/maps

Goal accepted with ID: 6d4452f87734497ba8bb7227143a127f

I waited for a few minutes, but get no result.

![Filepath](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_visual_slam/assets/57322445/6c6bee6f-f11b-421e-961b-83fbf7ebda3e)

![Message](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_visual_slam/assets/57322445/68ff6403-9dae-47e5-a829-da244aaa3ac6)

Edit:
I found, that the visual_slam_node throws this error:

[component_container-10] [INFO] [1686257562.293676663] [visual_slam_node]: elbrus: SaveMap /workspaces/isaac_ros-dev/maps
[component_container-10] [WARN] [1686257562.293733637] [visual_slam_node]: ELBRUS_SaveToSlamDb Error 6
[component_container-10] terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
[component_container-10]   what():  goal_handle attempted invalid transition from state ABORTED with event ABORT, at /opt/ros/humble/src/rcl/rcl_action/src/rcl_action/goal_handle.c:95
[ERROR] [component_container-10]: process has died [pid 9034, exit code -6, cmd '/opt/ros/humble/install/lib/rclcpp_components/component_container --ros-args -r __node:=vslam_container -r __ns:=/'].

Sorry if the solution is obvious, I am new to this.

Thanks in advance

**Comment by tom-deBach** [comment]
Hi @hsurya08,
I am a bit embarrassed, but I think I found part of my issue:
The Error Code I get says that the SLAM is not initialized.

The launch-file I used was a modified version of the nvblox example bringup:
"realsense_humans_example.launch.py", which launches a "vslam.launch.py" which sets the parameter:
'enable_localization_n_mapping': False

I changed it to true and now I get this:

admin@tegra-ubuntu:/workspaces/isaac_ros-dev$ ros2 action send_goal /visual_slam/save_map isaac_ros_visual_slam_interfaces/action/SaveMap "{map_url: /home/nvidia/workspaces/isaac_ros-dev/maps}" --feedback
Waiting for an action server to become available...
Sending goal:
     map_url: /home/nvidia/workspaces/isaac_ros-dev/maps

Goal accepted with ID: ac588a49dbc54e2eb423d9df2ecae8ae

Result:
    success: true
error: ''

Goal finished with status: SUCCEEDED

Although I still get this error in the [component_container-10]:
![Error_message](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_visual_slam/assets/57322445/a2cf155a-81ff-406e-bc56-e8de681ed121)

I don't know why it does not recognize the file path, but suspect it has something to do with the docker not being able to access the file path.

**Comment by ikhann** [comment]
@tom-deBach Hi! Have you solved this issue on the screenshot above related to the LMDB error and Failed to open Slam Database?
