### ISSUE TITLE
Save image status after IntelRealSense setup

### ISSUE THREAD

**Issue by reinzler** [NVIDIA-ISAAC-ROS/isaac_ros_visual_slam#94]
Hi, thanks for your awesome work, how its possible to save docker image to run after? If I understand correctly, if I will close the container and will rerun it with 
[Terminal 1] Launch the Docker container
cd ${ISAAC_ROS_WS}/src/isaac_ros_common && \
  ./scripts/run_dev.sh ${ISAAC_ROS_WS}
it will run with IntelRealSense (I have successfully installed  IntelRealSense ROS with this manual: https://github.com/NVIDIA-ISAAC-ROS/.github/blob/main/profile/realsense-setup.md). But if I will run the container from different Nvidia Orin Nano, It will run without IntelRealSense and I will have to start from scratch to install IntelRealSense again. I did docker commit and docker push to my docker hub account,  what should I change to start with mu own container with preinstalled IntelRealSense?
Thanks in advance

**Comment by jaiveersinghNV** [comment]
The Isaac ROS Docker image is built up as a series of layered Dockerfiles named in the pattern of `Dockerfile.foo` that you can find [here](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common/tree/main/docker). Then, we build up a specific sequence of those Dockerfiles based on the desired functionality (ex: `x86_64.ros2_humble.user` combines the `Dockerfile.x86_64`, `Dockerfile.ros2_humble`, and `Dockerfile.user` layers). For a few common combinations, we have provided prebuilt images available with a specific suffix to save users from needing to build on their machines (ex: `Dockerfile.x86_64.ros2_humble` links to a prebuilt image hosted on NVIDIA's container registry with exactly the `x86_64` and `ros2_humble` layers).

You can reuse this same pattern to support your own use case for enabling other Jetson devices to use a custom prebuilt container. For example, you could create a `Dockerfile.aarch64.ros2_humble.mine` file with only one line:
```dockerfile
FROM your_container_registry.io/foo/bar:latest
```

Then, simply set the `CONFIG_IMAGE_KEY` to `aarch64.ros2_humble.mine` as described [here](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common/blob/main/README.md#configuring-run_devsh). Any new Jetson with the same custom Dockerfile and config value will download your prebuilt image and save you some build time.
