### ISSUE TITLE
Issue on running the demo

### ISSUE THREAD

**Issue by pyrotank41** [NVIDIA-ISAAC-ROS/isaac_ros_visual_slam#96]
I am following the tutorial for Visual SLAM with Isaac Sim [here.](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_visual_slam#quickstart)
Upon running the following line:
```
source /workspaces/isaac_ros-dev/install/setup.bash && \
>   rviz2 -d src/isaac_ros_visual_slam/isaac_ros_visual_slam/rviz/default.cfg.rviz
```

i am getting the following error:
```
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Aborted (core dumped)
```

The remote platform where the docker is running: Ubuntu 22.04
Development computer (where I am working): Macbook pro m2 pro

XQuartz is running and forwarding the GUIs from the remote machine. 

Any suggestions on how i can fix the problem?

**Comment by jaiveersinghNV** [comment]
This sounds like an issue relating to display forwarding, and not something specific to Isaac ROS. This [thread](https://github.com/NVlabs/instant-ngp/discussions/300) suggests that you might need to install some additional dependencies inside the container to allow for display forwarding.

You might also consider using [Foxglove](https://foxglove.dev/) to visualize the data directly from a browser window on your Macbook Pro. I've also found that using a "headless" HDMI dummy plug installed on the remote computer can be helpful in solving weird display forwarding quirks.
